version: '3.1'
services:
  db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=Brian568
      volumes:
            - data-volume:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 568@duke.edu
      PGADMIN_DEFAULT_PASSWORD: Brian568
    ports:
      - '5050:80'
    depends_on:
      - db
  server:
    build: .
    command: python3 server.py
    volumes:
      - '.:/code'
    ports:
      - '34567:34567'
    depends_on:
      - db
  webapp:
    build: ./ups-webapp
    command: npm start
    ports:
      - '4000:4000'
    depends_on:
      - db
volumes:
  data-volume: null