version: '3.1'
services:
  db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=Brian568
      volumes:
            - data-volume:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 568@duke.edu
      PGADMIN_DEFAULT_PASSWORD: Brian568
    ports:
      - '5050:80'
    depends_on:
      - db
  ups-server:
    build: .
    command: python3 ups-service.py
    volumes:
      - '.:/code'
    ports:
      - '54321:54321'
    depends_on:
      - db
  world-server:
    build: .
    command: python3 world-service.py
    volumes:
      - '.:/code'
    depends_on:
      - db
volumes:
  data-volume: null